author: Signavio
exclude: [ Gemfile, Gemfile.lock, README.md ]
future: false
permalink: ":year/:title.html"
timezone: Europe/Berlin
title: Signavio Tech Blog
highlighter: rouge

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _scss
  #style: compressed
